---
- name: pip install...
  become: yes
  become_user: root
  pip: name={{item}} state=present
  with_items:
    - supervisor
    - supervisor-logging 

- name: ensure supervisor directory exists
  become: yes
  become_user: root
  with_items:
    - '{{supervisord_conf_dir}}'
    - '{{supervisord_profile_dir}}'
    - '{{supervisord_log_dir}}'
  file: >-
    path={{item}}
    mode=0755
    state=directory

- name: install supervisor config
  become: yes
  become_user: root
  with_items:
    - supervisord.conf
  template: >-
    src={{item}}.j2
    dest={{supervisord_etc_dir}}/{{item}}
    mode=0644
    
- name: install supervisor boot script
  become: yes
  become_user: root
  with_items:
    - boot-supervisord.sh
  template: >-
    src={{item}}.j2
    dest={{supervisord_bin_dir}}/{{item}}
    mode=0755
